### ISSUE TITLE
Random Sudden Deceleration on Path in Web Dashboard

### ISSUE THREAD

**Issue by Dylan-Powers** [msoe-vex/WebDashboard#22]
When making a Path in the Web Dashboard, occasionally the second to last point in a spline will have a much lower speed than the surrounding points. 

REPRODUCE: Make at least 1 new waypoint (at least two splines) and move the second waypoint around until you see occasional red on the spline near the second waypoint. Finesse it until the resting state of the path has the bugged red acceleration point.

**Comment by NathanDuPont** [comment]
It seems like this may have something to do with points being generated near infinitely close to others. I believe our acceleration and deceleration code is masking the problem as well, so for debugging, we likely want to remove this code to see what the true values are

**Comment by TrentonBowser** [comment]
Fixed in https://github.com/msoe-vex/WebDashboard/commit/34f01816c4c64a3d0f479c520e90c8b6c2fda56d
